// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoLXIj5y0Xi7RDIvDTitFFw9KfMdB6DTk',
    appId: '1:114935977587:web:ba17ff0f1e97c229bffc06',
    messagingSenderId: '114935977587',
    projectId: 'store-app-cabf4',
    authDomain: 'store-app-cabf4.firebaseapp.com',
    storageBucket: 'store-app-cabf4.appspot.com',
    measurementId: 'G-KHV22VWG2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkOnypjk7G3pG47-TYAAt_eBpwpiEIUmw',
    appId: '1:114935977587:android:0fe2e8cd6051e313bffc06',
    messagingSenderId: '114935977587',
    projectId: 'store-app-cabf4',
    storageBucket: 'store-app-cabf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx7nXws3nKQL083rIYbkkdnb6ptK-GNR0',
    appId: '1:114935977587:ios:c6ddd64e9ec7352dbffc06',
    messagingSenderId: '114935977587',
    projectId: 'store-app-cabf4',
    storageBucket: 'store-app-cabf4.appspot.com',
    iosBundleId: 'com.example.training',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx7nXws3nKQL083rIYbkkdnb6ptK-GNR0',
    appId: '1:114935977587:ios:3efcf82f83d1c103bffc06',
    messagingSenderId: '114935977587',
    projectId: 'store-app-cabf4',
    storageBucket: 'store-app-cabf4.appspot.com',
    iosBundleId: 'com.example.training.RunnerTests',
  );
}
